create table IF NOT EXISTS "MESSAGES" (
  MESSAGE_ID INTEGER IDENTITY,
  MESSAGE_FROM_NAME VARCHAR NOT NULL,
  MESSAGE VARCHAR NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL
);

create table IF NOT EXISTS "USERS" (
  ID INTEGER IDENTITY,
  NAME VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL
);
